### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by denizzzka** [jll63/openmethods.d#10]
```
../openmethods.d/source/openmethods.d(710,12): Deprecation: struct std.datetime.StopWatch is deprecated - Use std.datetime.stopwatch.StopWatch.
../openmethods.d/source/openmethods.d(1199,15): Deprecation: struct std.datetime.StopWatch is deprecated - Use std.datetime.stopwatch.StopWatch.
```

**Comment by jll63** [comment]
Ready in https://github.com/jll63/openmethods.d/tree/use-new-stopwatch but gdc is not up to it yet.

**Comment by denizzzka** [comment]
Huh, ok.
And thanks for this project - it is very helpful! Maybe this mechanism shold become a part of any OOP language.

**Comment by jll63** [comment]
Thanks.
Open methods are native in several languages and object systems. The Common Lisp Object System was, AFAIK, the first implementation of the idea. Clojure, Dylan, Cecil, Julia, TADS, etc all implement polymorphism via open multi-methods.
