### ISSUE TITLE
ref parameters in virtual methods?

### ISSUE THREAD

**Issue by uqtredd1** [jll63/openmethods.d#13]
Is it possible to use ref parameters in virtual methods?

```D
interface Base {}

void method(virtual!Base, ref T) ;
```

Does not compile with "expression expected, not ref", although T* compiles without errors.

**Comment by jll63** [comment]
I am working on this issue. I tried to combine the fix with a simplification but D is resisting.

**Comment by jll63** [comment]
After several attempts, I am not sure it is possible to support this. Closing for now.

**Comment by jll63** [comment]
Working on this, I think I nailed it, at the cost of using a lot of string mixins.
See branch https://github.com/jll63/openmethods.d/tree/parameter-storage-class.

**Comment by jll63** [comment]
Fixed in v1.2.0.
