### ISSUE TITLE
Using `module foo.bar` breaks compilation.

### ISSUE THREAD

**Issue by ghost** [jll63/openmethods.d#6]
The following piece doesn't compile:
```
/* source/fileName.d */
module app.someModule;

import openmethods;
mixin(registerMethods);

void main()
{
}
```
A superficial fix is to put parentheses around `%s`s in `registerMethods`, but this just fixes compilation, and I'm not familiar with the source enough to tell if that's the only place that needs changes (that's why I'm opening an issue instead of making a pull request with the fix)

**Comment by jll63** [comment]
Good catch, and your fix is correct. You send me a PR? That will make you an official contributor ;-)
